<a href="https://colab.research.google.com/github/Konica24/PyTorch-Codemy/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**TENSORS**



*   A torch.Tensor is a multi-dimensional matrix containing elements of a single data type.
*   Similar to Numpy Arrays, but full of fun things that make them work better on GPU's (vs regular CPU's).


*   default data type of float32.
*   More suitable for deep learning than a numpy array.







In [1]:
import torch
import numpy as np

**LISTS**

In [3]:
my_list = [[1,2,3,4,5], [6,7,8, 9, 10]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

**NUMPY** **ARRAYS**

In [5]:
np1 = np.random.rand(3,4)
np1

array([[0.84230646, 0.83082975, 0.39577247, 0.29109335],
       [0.45997531, 0.6387949 , 0.24345856, 0.33839967],
       [0.47614083, 0.37408915, 0.19428546, 0.01050305]])

In [6]:
np1.dtype

dtype('float64')

**TENSORS**

In [12]:
tensor_2d = torch.randn(3,4)
tensor_2d
#tensor_2d.dtype

tensor([[ 0.9627, -0.8910,  1.0259,  0.5842],
        [-0.3505,  1.3016, -0.1618,  1.1785],
        [-1.8298,  1.0281,  1.3008,  0.0412]])

In [9]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [10]:
## Create tensor out of numpy array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.8423, 0.8308, 0.3958, 0.2911],
        [0.4600, 0.6388, 0.2435, 0.3384],
        [0.4761, 0.3741, 0.1943, 0.0105]], dtype=torch.float64)